// Next
import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Components
import Footer from "@/components/footer/footer";

// Styles
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <section id="game">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
